name: teste2223
on:
   workflow_dispatch:
jobs:
    deploy:
         name: deploy
         runs-on: ubuntu-latest
         steps:
           - name: checkout
             uses: actions/checkout@v3

          # - name: teste2
           #  run: |
            #      echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
             #     echo "AWS_SECRET_ACCESS_KEY =${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV


          # - name: teste3
           #  run: echo APP_NAME 
           
           - name: set credentials aws
             env: 
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
             with:
               aws-access-key-id: $AWS_ACCESS_KEY_ID
               aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
               aws-region: ${{ vars.AWS_REGION }}

           - name: lista bucket
             run: aws s3 ls