name: test3
on:
   workflow_dispatch:
jobs:
    test3:
         name: test3
         runs-on: ubuntu-latest
         steps:
          - name: kvouthtestd
            uses: joaov-barbosa/demo-kvouth-v@v2
            with:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION: ${{ vars.AWS_REGION }}