name: test3
on:
   workflow_dispatch:
jobs:
    test3:
         name: test3
         runs-on: ubuntu-latest
         steps:
          - name: kvouthtestd
            uses: joaov-barbosa/sharing-workflow-demo/.github/workflows/test.yml@master
            with:
              aws-region-d: ${{ vars.AWS_REGION }}
            secrets:
              aws-access-key-id-d: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key-d: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             