name: test3
on:
   workflow_dispatch:
jobs:
    test3:
         name: test3
         runs-on: ubuntu-latest
         steps:
          - name: kvouthtestd
            uses: joaov-barbosa/demo-kvouth-v@v3
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ vars.AWS_REGION }}