name: test3
on:
   workflow_dispatch:
jobs:
    test3:
         name: test3
         runs-on: ubuntu-latest
         steps:
           - name: checkout
             uses: actions/checkout@v3

           - name: credeciais aws
             run: ./test.sh
